---
downloads: ~/.ansible-downloads/

configure_sudoers: yes
configure_prefs: yes
configure_osx: yes

dotfiles_repo: https://github.com/hgylfason/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/work/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitconfig
  - .gitignore
  - .inputrc
  - .osx
  - .tmux.conf
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - gettext
  - git
  - git-flow
  - httpie
  - python
  - npm
  - nvm
  - ssh-copy-id
  - cowsay
  - readline
  - subversion
  - tmux
  - openssl
  - python3
  - tree
  - pv
  - wget

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/php
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - alfred
  - bartender
  - dash
  - disk-inventory-x
  - docker
  - dropbox
  - firefox
  - flux
  - gitup
  - google-chrome
  - iterm2
  - java
  - libreoffice
  - macvim
  - mailmate
  - pycharm
  - screenhero
  - skype-for-business
  - slack
  - spectacle
  - spotify
  - transmission
#  - vagrant  # disabled because the latest version does not work
  - virtualbox
# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_app_ids: []
#  - 407963104 # Pixelmator
#  - 585829637 # Todoist
#  - 568494494 # Pocket
#  - 552777084 # Radio
#  - 429449079 # Patterns
mas_email: ""
mas_password: ""

# these are apps that need to be installed manually
download_dest: ~/Downloads
download_apps:
  - https://releases.hashicorp.com/vagrant/1.9.0/vagrant_1.9.0.dmg
