---
downloads: ~/.ansible-downloads/

configure_sudoers: yes
configure_prefs: yes
configure_osx: yes

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitconfig
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - gettext
  - git
  - git-flow
  - httpie
  - python
  - npm
  - nvm
  - ssh-copy-id
  - cowsay
  - readline
  - subversion
  - tmux
  - openssl
  - python3
  - tree
  - pv
  - wget

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/php
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alfred
  - bartender
  - dash
  - docker
  - dropbox
  - firefox
  - flux
  - google-chrome
  - iterm2
  - java
  - macvim
  - mailmate
  - pycharm
  - screenhero
  - skype-for-business
  - slack
  - spotify
  - transmission
  - vagrant
  - virtualbox

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_app_ids:
  - 407963104 # Pixelmator
  - 585829637 # Todoist
  - 568494494 # Pocket
  - 552777084 # Radio
mas_email: ""
mas_password: ""
