---
# Custom Terminal theme.
- name: Get current Terminal profile.
  shell: defaults read com.apple.terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false
  always_run: yes

- name: Ensure custom Terminal profile is added.
  shell: open files/terminal/JJG-Term.terminal
  changed_when: false
  when: "'JJG-Term' not in terminal_theme.stdout"

# TODO: This doesn't work in Yosemite. Consider a different solution?
- name: Ensure custom Terminal profile is set as default.
  shell: "{{ item }}"
  with_items:
    - defaults write com.apple.terminal 'Default Window Settings' -string JJG-Term
    - defaults write com.apple.terminal 'Startup Window Settings' -string JJG-Term
  changed_when: false
  when: "'JJG-Term' not in terminal_theme.stdout"

# Sudoers configuration (enables more convenient Vagrant usage).
- name: Copy sudoers configuration into place.
  copy:
    src: files/etc/sudoers
    dest: /etc/sudoers
    mode: 0440
    validate: 'visudo -cf %s'
  become: yes
  when: configure_sudoers

- name: Install oh-my-zsh for zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

- name: Install Vundle as Vim package manager
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
    version: master

- name: Add solarized colorscheme to vim
  copy:
    src: files/vim/.vim
    dest: ~/
    mode: 0755

- name: Create development directory for Hugfimi at the correct location
  copy:
    src: files/hugfimi/
    dest: ~/hugfimi/
    mode: 0775
